package(default_visibility = ["//iris:__pkg__"])

cc_library(
    name = "test_util",
    hdrs = ["test_util.h"],
    deps = [
        "//iris:iris",
        "@com_google_googletest//:gtest_main"
    ],
    testonly = 1,
)