
#ifndef IRISPHYSXTOOLKITAPI_H
#define IRISPHYSXTOOLKITAPI_H

#ifdef IRISPHYSXTOOLKIT_BUILT_AS_STATIC
#  define IRISPHYSXTOOLKITAPI
#  define IRISPHYSXTOOLKIT_NO_EXPORT
#else
#  ifndef IRISPHYSXTOOLKITAPI
#    ifdef irisphysxtoolkit_EXPORTS
        /* We are building this library */
#      define IRISPHYSXTOOLKITAPI __declspec(dllexport)
#    else
        /* We are using this library */
#      define IRISPHYSXTOOLKITAPI __declspec(dllimport)
#    endif
#  endif

#  ifndef IRISPHYSXTOOLKIT_NO_EXPORT
#    define IRISPHYSXTOOLKIT_NO_EXPORT 
#  endif
#endif

#ifndef IRISPHYSXTOOLKIT_DEPRECATED
#  define IRISPHYSXTOOLKIT_DEPRECATED __declspec(deprecated)
#endif

#ifndef IRISPHYSXTOOLKIT_DEPRECATED_EXPORT
#  define IRISPHYSXTOOLKIT_DEPRECATED_EXPORT IRISPHYSXTOOLKITAPI IRISPHYSXTOOLKIT_DEPRECATED
#endif

#ifndef IRISPHYSXTOOLKIT_DEPRECATED_NO_EXPORT
#  define IRISPHYSXTOOLKIT_DEPRECATED_NO_EXPORT IRISPHYSXTOOLKIT_NO_EXPORT IRISPHYSXTOOLKIT_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define IRISPHYSXTOOLKIT_NO_DEPRECATED
#endif

#endif
