/*++

Copyright (c) 2018 Brad Weinberger

Module Name:

    status.h

Abstract:

    The status type and constants used by Iris.

--*/

#ifndef _IRIS_STATUS_
#define _IRIS_STATUS_

#include "iris/sal.h"

#include <stdint.h>

typedef _Return_type_success_(return == 0) uint8_t ISTATUS;

#define ISTATUS_SUCCESS              0x00
#define ISTATUS_ALLOCATION_FAILED    0x01
#define ISTATUS_ARITHMETIC_ERROR     0x02
#define ISTATUS_INTEGER_OVERFLOW     0x03
#define ISTATUS_NO_MORE_DATA         0x04
#define ISTATUS_IO_ERROR             0x05

#define ISTATUS_INVALID_ARGUMENT_00  0x80
#define ISTATUS_INVALID_ARGUMENT_01  0x81
#define ISTATUS_INVALID_ARGUMENT_02  0x82
#define ISTATUS_INVALID_ARGUMENT_03  0x83
#define ISTATUS_INVALID_ARGUMENT_04  0x84
#define ISTATUS_INVALID_ARGUMENT_05  0x85
#define ISTATUS_INVALID_ARGUMENT_06  0x86
#define ISTATUS_INVALID_ARGUMENT_07  0x87
#define ISTATUS_INVALID_ARGUMENT_08  0x88
#define ISTATUS_INVALID_ARGUMENT_09  0x89
#define ISTATUS_INVALID_ARGUMENT_10  0x8A
#define ISTATUS_INVALID_ARGUMENT_11  0x8B
#define ISTATUS_INVALID_ARGUMENT_12  0x8C
#define ISTATUS_INVALID_ARGUMENT_13  0x8D
#define ISTATUS_INVALID_ARGUMENT_14  0x8E
#define ISTATUS_INVALID_ARGUMENT_15  0x8F
#define ISTATUS_INVALID_ARGUMENT_16  0x90
#define ISTATUS_INVALID_ARGUMENT_17  0x91
#define ISTATUS_INVALID_ARGUMENT_18  0x92
#define ISTATUS_INVALID_ARGUMENT_19  0x93
#define ISTATUS_INVALID_ARGUMENT_20  0x94
#define ISTATUS_INVALID_ARGUMENT_21  0x95
#define ISTATUS_INVALID_ARGUMENT_22  0x96
#define ISTATUS_INVALID_ARGUMENT_23  0x97
#define ISTATUS_INVALID_ARGUMENT_24  0x98
#define ISTATUS_INVALID_ARGUMENT_25  0x99
#define ISTATUS_INVALID_ARGUMENT_26  0x9A
#define ISTATUS_INVALID_ARGUMENT_27  0x9B
#define ISTATUS_INVALID_ARGUMENT_28  0x9C
#define ISTATUS_INVALID_ARGUMENT_29  0x9D
#define ISTATUS_INVALID_ARGUMENT_30  0x9E
#define ISTATUS_INVALID_ARGUMENT_31  0x9F

#define ISTATUS_INVALID_ARGUMENT_COMBINATION_00  0xA0
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_01  0xA1
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_02  0xA2
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_03  0xA3
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_04  0xA4
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_05  0xA5
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_06  0xA6
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_07  0xA7
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_08  0xA8
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_09  0xA9
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_10  0xAA
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_11  0xAB
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_12  0xAC
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_13  0xAD
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_14  0xAE
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_15  0xAF
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_16  0xB0
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_17  0xB1
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_18  0xB2
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_19  0xB3
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_20  0xB4
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_21  0xB5
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_22  0xB6
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_23  0xB7
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_24  0xB8
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_25  0xB9
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_26  0xBA
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_27  0xBB
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_28  0xBC
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_29  0xBD
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_30  0xBE
#define ISTATUS_INVALID_ARGUMENT_COMBINATION_31  0xBF

#endif // _IRIS_STATUS_