
#ifndef IRISPHYSXPLUSPLUSAPI_H
#define IRISPHYSXPLUSPLUSAPI_H

#ifdef IRISPHYSXPLUSPLUS_BUILT_AS_STATIC
#  define IRISPHYSXPLUSPLUSAPI
#  define IRISPHYSXPLUSPLUS_NO_EXPORT
#else
#  ifndef IRISPHYSXPLUSPLUSAPI
#    ifdef irisphysxplusplus_EXPORTS
        /* We are building this library */
#      define IRISPHYSXPLUSPLUSAPI __declspec(dllexport)
#    else
        /* We are using this library */
#      define IRISPHYSXPLUSPLUSAPI __declspec(dllimport)
#    endif
#  endif

#  ifndef IRISPHYSXPLUSPLUS_NO_EXPORT
#    define IRISPHYSXPLUSPLUS_NO_EXPORT 
#  endif
#endif

#ifndef IRISPHYSXPLUSPLUS_DEPRECATED
#  define IRISPHYSXPLUSPLUS_DEPRECATED __declspec(deprecated)
#endif

#ifndef IRISPHYSXPLUSPLUS_DEPRECATED_EXPORT
#  define IRISPHYSXPLUSPLUS_DEPRECATED_EXPORT IRISPHYSXPLUSPLUSAPI IRISPHYSXPLUSPLUS_DEPRECATED
#endif

#ifndef IRISPHYSXPLUSPLUS_DEPRECATED_NO_EXPORT
#  define IRISPHYSXPLUSPLUS_DEPRECATED_NO_EXPORT IRISPHYSXPLUSPLUS_NO_EXPORT IRISPHYSXPLUSPLUS_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define IRISPHYSXPLUSPLUS_NO_DEPRECATED
#endif

#endif
