load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//iris/bsdfs:__subpackages__"])

cc_library(
    name = "local",
    hdrs = ["local.h"],
    deps = [
        "//iris:vector",
    ],
)
