
#ifndef IRISADVANCEDPLUSPLUSAPI_H
#define IRISADVANCEDPLUSPLUSAPI_H

#ifdef IRISADVANCEDPLUSPLUS_BUILT_AS_STATIC
#  define IRISADVANCEDPLUSPLUSAPI
#  define IRISADVANCEDPLUSPLUS_NO_EXPORT
#else
#  ifndef IRISADVANCEDPLUSPLUSAPI
#    ifdef irisadvancedplusplus_EXPORTS
        /* We are building this library */
#      define IRISADVANCEDPLUSPLUSAPI __declspec(dllexport)
#    else
        /* We are using this library */
#      define IRISADVANCEDPLUSPLUSAPI __declspec(dllimport)
#    endif
#  endif

#  ifndef IRISADVANCEDPLUSPLUS_NO_EXPORT
#    define IRISADVANCEDPLUSPLUS_NO_EXPORT 
#  endif
#endif

#ifndef IRISADVANCEDPLUSPLUS_DEPRECATED
#  define IRISADVANCEDPLUSPLUS_DEPRECATED __declspec(deprecated)
#endif

#ifndef IRISADVANCEDPLUSPLUS_DEPRECATED_EXPORT
#  define IRISADVANCEDPLUSPLUS_DEPRECATED_EXPORT IRISADVANCEDPLUSPLUSAPI IRISADVANCEDPLUSPLUS_DEPRECATED
#endif

#ifndef IRISADVANCEDPLUSPLUS_DEPRECATED_NO_EXPORT
#  define IRISADVANCEDPLUSPLUS_DEPRECATED_NO_EXPORT IRISADVANCEDPLUSPLUS_NO_EXPORT IRISADVANCEDPLUSPLUS_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define IRISADVANCEDPLUSPLUS_NO_DEPRECATED
#endif

#endif
