package(default_visibility = ["//visibility:public"])

cc_library(
    name = "physx_sample_tracer",
    hdrs = ["physx_sample_tracer.h"],
    srcs = ["physx_sample_tracer.c"],
    deps = [
        "//iris_camera:iris_camera",
        "//iris_physx:iris_physx",
    ],
)